# ostrov's colours for qutebrowser, written by ostrov as its look changes
bg, view, card, fg, dim = "{{bg}}", "{{view}}", "{{card}}", "{{fg}}", "{{dim}}"
accent, ink, urgent = "{{accent}}", "{{ink}}", "{{urgent}}"
c.colors.webpage.preferred_color_scheme = "{{mode}}"
c.colors.statusbar.normal.bg = bg
c.colors.statusbar.normal.fg = fg
c.colors.statusbar.command.bg = view
c.colors.statusbar.command.fg = fg
c.colors.statusbar.insert.bg = accent
c.colors.statusbar.insert.fg = ink
c.colors.statusbar.url.success.https.fg = fg
c.colors.tabs.bar.bg = bg
c.colors.tabs.even.bg = card
c.colors.tabs.odd.bg = card
c.colors.tabs.even.fg = dim
c.colors.tabs.odd.fg = dim
c.colors.tabs.selected.even.bg = accent
c.colors.tabs.selected.odd.bg = accent
c.colors.tabs.selected.even.fg = ink
c.colors.tabs.selected.odd.fg = ink
c.colors.completion.even.bg = view
c.colors.completion.odd.bg = view
c.colors.completion.fg = fg
c.colors.completion.category.bg = card
c.colors.completion.category.fg = fg
c.colors.completion.item.selected.bg = accent
c.colors.completion.item.selected.fg = ink
c.colors.completion.item.selected.border.top = accent
c.colors.completion.item.selected.border.bottom = accent
c.colors.completion.match.fg = accent
c.colors.hints.bg = accent
c.colors.hints.fg = ink
c.colors.messages.error.bg = urgent
c.colors.messages.info.bg = view
