-- ostrov's colours for Neovim, written by ostrov as its look changes: :colorscheme ostrov
vim.cmd("highlight clear")
vim.g.colors_name = "ostrov"
vim.o.background = "{{mode}}"
local c = {
  bg = "{{bg}}", view = "{{view}}", card = "{{card}}", fg = "{{fg}}", dim = "{{dim}}",
  accent = "{{accent}}", ink = "{{ink}}", urgent = "{{urgent}}",
  red = "{{ansi1}}", green = "{{ansi2}}", yellow = "{{ansi3}}", blue = "{{ansi4}}",
  magenta = "{{ansi5}}", cyan = "{{ansi6}}",
}
local hl = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end
-- the editor: its ground the terminal's, so see-through as the bar is
hl("Normal", { fg = c.fg })
hl("NormalNC", { fg = c.fg })
hl("NormalFloat", { fg = c.fg, bg = c.view })
hl("FloatBorder", { fg = c.dim, bg = c.view })
hl("SignColumn", {})
hl("LineNr", { fg = c.dim })
hl("CursorLineNr", { fg = c.accent, bold = true })
hl("CursorLine", { bg = c.card })
hl("ColorColumn", { bg = c.card })
hl("Visual", { fg = c.ink, bg = c.accent })
hl("Search", { fg = c.ink, bg = c.yellow })
hl("IncSearch", { fg = c.ink, bg = c.accent })
hl("CurSearch", { link = "IncSearch" })
hl("MatchParen", { fg = c.accent, bold = true })
hl("Pmenu", { fg = c.fg, bg = c.view })
hl("PmenuSel", { fg = c.ink, bg = c.accent })
hl("PmenuThumb", { bg = c.dim })
hl("StatusLine", { fg = c.fg, bg = c.card })
hl("StatusLineNC", { fg = c.dim, bg = c.card })
hl("TabLine", { fg = c.dim, bg = c.card })
hl("TabLineSel", { fg = c.ink, bg = c.accent })
hl("TabLineFill", {})
hl("WinSeparator", { fg = c.card })
hl("VertSplit", { link = "WinSeparator" })
hl("Folded", { fg = c.dim, bg = c.card })
hl("NonText", { fg = c.dim })
hl("Whitespace", { fg = c.card })
hl("Directory", { fg = c.blue })
hl("Title", { fg = c.accent, bold = true })
hl("ErrorMsg", { fg = c.urgent })
hl("WarningMsg", { fg = c.yellow })
hl("MoreMsg", { fg = c.green })
hl("Question", { fg = c.green })
hl("DiffAdd", { fg = c.green })
hl("DiffChange", { fg = c.yellow })
hl("DiffDelete", { fg = c.red })
hl("DiffText", { fg = c.blue, bold = true })
-- the code
hl("Comment", { fg = c.dim, italic = true })
hl("Constant", { fg = c.yellow })
hl("String", { fg = c.green })
hl("Character", { link = "String" })
hl("Number", { fg = c.yellow })
hl("Boolean", { fg = c.yellow })
hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.blue })
hl("Statement", { fg = c.magenta })
hl("Keyword", { fg = c.magenta })
hl("Operator", { fg = c.cyan })
hl("PreProc", { fg = c.cyan })
hl("Type", { fg = c.accent })
hl("Special", { fg = c.cyan })
hl("Delimiter", { fg = c.dim })
hl("Todo", { fg = c.ink, bg = c.accent, bold = true })
hl("Error", { fg = c.urgent })
hl("DiagnosticError", { fg = c.urgent })
hl("DiagnosticWarn", { fg = c.yellow })
hl("DiagnosticInfo", { fg = c.blue })
hl("DiagnosticHint", { fg = c.cyan })
hl("@variable", { fg = c.fg })
hl("@property", { fg = c.fg })
hl("@function.builtin", { fg = c.cyan })
hl("@type.builtin", { fg = c.accent })
hl("@punctuation", { fg = c.dim })
